name: Test-Webserv-Reachability

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: start Webserver
      run: bash -ec 'nohup ./webserv resources/configs/conf1.cnf' < /dev/null &
    - name: Check Reachability of webserv
      run: bash wait-for-startup.sh

